### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by teocomi** [radumg/AEC-hackathon-Dynamo-Workshop#16]
Hey guys, 

I see this repo keeps being used and since it started off https://github.com/teocomi/dug-dynamo-unchained maybe some credits could be added? 
Or even better it could be hosted by an org account instead?

Cheers

**Comment by radumg** [comment]
Hey @teocomi , of course, i honestly thought we had either forked (which would have a notice) or had a section about it, for when we did it for Berlin.  Maybe it was in the during the class only ?

In any case, added a notice front & center until we figure out where the best place would be for it (what org?), sound ok ?

**Comment by teocomi** [comment]
Cheers man!
